### ISSUE TITLE
KRR install missing python modules aiostream and slack-sdk

### ISSUE THREAD

**Issue by calvincarter-ping** [robusta-dev/krr#125]
After manually installing KRR https://github.com/robusta-dev/krr#manual-installation, I noticed the following modules were missing:

- aiostream 
- slack-sdk

**To Reproduce**
1. Follow manual install [instructions](https://github.com/robusta-dev/krr#manual-installation)
2. See the error for **slack-sdk**. (if you manually install via pip the error goes away https://pypi.org/project/slack-sdk/)
4. If step 2 is resolved using workaround you will then see the error for **aiostream**. (if you manually install via pip error goes away https://pypi.org/project/aiostream/)

**Expected behavior**
**slack-sdk** and **aiostream** installed properly via requirements.txt file.

**Suggested Fix**
Add these 2 dependencies **slack-sdk** and **aiostream**  to the [requirements.txt](https://github.com/robusta-dev/krr/blob/main/requirements.txt) file

**Error Messages**

**slack-sdk**
```
python3 krr.py --help          
               
Traceback (most recent call last):
  File "/Users/calvincarter/_programming/docker/development/krr_install/krr/krr.py", line 1, in <module>
    from robusta_krr import run
  File "/Users/calvincarter/_programming/docker/development/krr_install/krr/robusta_krr/__init__.py", line 1, in <module>
    from .main import run
  File "/Users/calvincarter/_programming/docker/development/krr_install/krr/robusta_krr/main.py", line 16, in <module>
    from robusta_krr.core.runner import Runner
  File "/Users/calvincarter/_programming/docker/development/krr_install/krr/robusta_krr/core/runner.py", line 6, in <module>
    from slack_sdk import WebClient
ModuleNotFoundError: No module named 'slack_sdk'
```

**aiostream** 
```
 python3 krr.py --help 
Traceback (most recent call last):
  File "/Users/calvincarter/_programming/docker/development/krr_install/krr/krr.py", line 1, in <module>
    from robusta_krr import run
  File "/Users/calvincarter/_programming/docker/development/krr_install/krr/robusta_krr/__init__.py", line 1, in <module>
    from .main import run
  File "/Users/calvincarter/_programming/docker/development/krr_install/krr/robusta_krr/main.py", line 16, in <module>
    from robusta_krr.core.runner import Runner
  File "/Users/calvincarter/_programming/docker/development/krr_install/krr/robusta_krr/core/runner.py", line 10, in <module>
    from robusta_krr.core.integrations.kubernetes import KubernetesLoader
  File "/Users/calvincarter/_programming/docker/development/krr_install/krr/robusta_krr/core/integrations/kubernetes.py", line 4, in <module>
    import aiostream
ModuleNotFoundError: No module named 'aiostream'

```

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Version [Ventura 13.5]

**Comment by Avi-Robusta** [comment]
Fixed in https://github.com/robusta-dev/krr/pull/124
