### ISSUE TITLE
K8s RBAC issue on namespace scope

### ISSUE THREAD

**Issue by rohank07** [robusta-dev/krr#207]
**Describe the bug**

I am trying to run krr without cluster-admin permissions. This doesn't seem possible with the tool trying to get dameonsets, hpa, deployments, jobs etc. using on all namespaces on the cluster even though I am scoping it to a specific namespace. Looking to modify the source code to avoid calling `all_namespaces_request` function in __init.__.py Looking for additional guidance if this is the way to go about this

**Are you interested in contributing a fix for this?**
Yes

**Comment by bondido** [comment]
Shouldn't it be possible to run krr not "touching" kubectl context in any way?
If we have all data available with prometheus metrics, shouldn't it be enough to only get access to it?

If no, then there should be info in the docs regarding minimal required RBAC privileges.

**Comment by rohank07** [comment]
I've commented out https://github.com/robusta-dev/krr/blob/main/robusta_krr/core/integrations/kubernetes/__init__.py#L66
and https://github.com/robusta-dev/krr/blob/main/robusta_krr/core/integrations/kubernetes/__init__.py#L134

After commenting out those lines it fails on GET request calling `self.list_namespaced_deployment_with_http_info`
Stack trace
```
Error 403 listing Deployment in cluster <>: Forbidden                       __init__.py:198
                    Traceback (most recent call last):                                                                                     
                      File "/home/rohank/Code/krr/robusta_krr/core/integrations/kubernetes/__init__.py", line 185, in                      
                    _list_workflows                                                                                                        
                        ret_single = await task                                                                                            
                      File "/usr/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one                                              
                        return f.result()  # May raise f.exception().                                                                      
                      File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run                                             
                        result = self.fn(*self.args, **self.kwargs)                                                                        
                      File "/home/rohank/Code/krr/robusta_krr/core/integrations/kubernetes/__init__.py", line 174, in                      
                    <lambda>                                                                                                               
                        lambda ns=namespace: namespaced_request(                                                                           
                      File "/home/rohank/.local/lib/python3.10/site-packages/kubernetes/client/api/apps_v1_api.py", line                   
                    3345, in list_namespaced_deployment                                                                                    
                        return self.list_namespaced_deployment_with_http_info(namespace, **kwargs)  # noqa: E501                           
                      File "/home/rohank/.local/lib/python3.10/site-packages/kubernetes/client/api/apps_v1_api.py", line                   
                    3460, in list_namespaced_deployment_with_http_info                                                                     
                        return self.api_client.call_api(                                                                                   
                      File "/home/rohank/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 348, in                
                    call_api                                                                                                               
                        return self.__call_api(resource_path, method,                                                                      
                      File "/home/rohank/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 180, in                
                    __call_api                                                                                                             
                        response_data = self.request(                                                                                      
                      File "/home/rohank/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 373, in                
                    request                                                                                                                
                        return self.rest_client.GET(url,                                                                                   
                      File "/home/rohank/.local/lib/python3.10/site-packages/kubernetes/client/rest.py", line 241, in GET                  
                        return self.request("GET", url,                                                                                    
                      File "/home/rohank/.local/lib/python3.10/site-packages/kubernetes/client/rest.py", line 235, in                      
                    request                                                                                                                
                        raise ApiException(http_resp=r)                                                                                    
                    kubernetes.client.exceptions.ApiException: (403)                                                                       
                    Reason: Forbidden                                                                                                      
                    HTTP response headers: HTTPHeaderDict({'Audit-Id': 'f6808425-d0eb-468c-a738-45af5c485043',                             
                    'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options':                    
                    'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '36d3ffc5-c72a-4989-920f-c53c5be85162',                                   
                    'X-Kubernetes-Pf-Prioritylevel-Uid': '03f4e52a-c663-4840-98e3-5070f58d9b88', 'Date': 'Tue, 13 Feb 2024                 
                    14:26:01 GMT', 'Content-Length': '315'})                                                                               
                    HTTP response body:                                                                                                    
                    {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"deployments.apps is                     
                    forbidden: User \"<user>\" cannot list resource \"deployments\" in API group \"apps\" in                 
                    the namespace                                                                                                          
                    \"<namespace>\"","reason":"Forbidden","details":{"group":"apps","kind":"deployments"},"code":403}      

``` 

403s are also thrown for dameonSet, job and statefulset. This works fine when I have cluster-admin privileges' on the cluster

**Comment by rohank07** [comment]
I've commented out https://github.com/robusta-dev/krr/blob/main/robusta_krr/core/integrations/kubernetes/__init__.py#L66
and https://github.com/robusta-dev/krr/blob/main/robusta_krr/core/integrations/kubernetes/__init__.py#L134

After commenting out those lines it fails on GET request calling `self.list_namespaced_deployment_with_http_info`
Stack trace
```
Error 403 listing Deployment in cluster <>: Forbidden                       __init__.py:198
                    Traceback (most recent call last):                                                                                     
                      File "/home/Code/krr/robusta_krr/core/integrations/kubernetes/__init__.py", line 185, in                      
                    _list_workflows                                                                                                        
                        ret_single = await task                                                                                            
                      File "/usr/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one                                              
                        return f.result()  # May raise f.exception().                                                                      
                      File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run                                             
                        result = self.fn(*self.args, **self.kwargs)                                                                        
                      File "/home/Code/krr/robusta_krr/core/integrations/kubernetes/__init__.py", line 174, in                      
                    <lambda>                                                                                                               
                        lambda ns=namespace: namespaced_request(                                                                           
                      File "/home/.local/lib/python3.10/site-packages/kubernetes/client/api/apps_v1_api.py", line                   
                    3345, in list_namespaced_deployment                                                                                    
                        return self.list_namespaced_deployment_with_http_info(namespace, **kwargs)  # noqa: E501                           
                      File "/home/.local/lib/python3.10/site-packages/kubernetes/client/api/apps_v1_api.py", line                   
                    3460, in list_namespaced_deployment_with_http_info                                                                     
                        return self.api_client.call_api(                                                                                   
                      File "/home/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 348, in                
                    call_api                                                                                                               
                        return self.__call_api(resource_path, method,                                                                      
                      File "/home/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 180, in                
                    __call_api                                                                                                             
                        response_data = self.request(                                                                                      
                      File "/home/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 373, in                
                    request                                                                                                                
                        return self.rest_client.GET(url,                                                                                   
                      File "/home/.local/lib/python3.10/site-packages/kubernetes/client/rest.py", line 241, in GET                  
                        return self.request("GET", url,                                                                                    
                      File "/home/.local/lib/python3.10/site-packages/kubernetes/client/rest.py", line 235, in                      
                    request                                                                                                                
                        raise ApiException(http_resp=r)                                                                                    
                    kubernetes.client.exceptions.ApiException: (403)                                                                       
                    Reason: Forbidden                                                                                                      
                    HTTP response headers: HTTPHeaderDict({'Audit-Id': '',                             
                    'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options':                    
                    'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '',                                   
                    'X-Kubernetes-Pf-Prioritylevel-Uid': '', 'Date': 'Tue, 13 Feb 2024                 
                    14:26:01 GMT', 'Content-Length': '315'})                                                                               
                    HTTP response body:                                                                                                    
                    {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"deployments.apps is                     
                    forbidden: User \"<user>\" cannot list resource \"deployments\" in API group \"apps\" in                 
                    the namespace                                                                                                          
                    \"<namespace>\"","reason":"Forbidden","details":{"group":"apps","kind":"deployments"},"code":403}      

``` 

403s are also thrown for dameonSet, job and statefulset. This works fine when I have cluster-admin privileges' on the cluster

**Comment by aantn** [comment]
Where it says "<namespace>", does it actually say that, or did you sanitize the logs?

**Comment by rohank07** [comment]
Yup, I sanitized the logs

**Comment by aantn** [comment]
This is strange. Does the equivalent `kubectl get` command work in the same shell, without cluster-admin?

Is it possible you have multiple kubectl contexts and the wrong context is being picked up here?

**Comment by rohank07** [comment]
Turns out when I scope it to a specific namespace that I have access to (without cluster-admin)
It throws me a 403 on services at the cluster scope.
python3 krr.py simple -n test-namespace

```
 HTTP response body:                                                                                                    
                    {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services is forbidden:                  
                    User \"<USER>\" cannot list resource \"services\" in API group \"\" at the cluster                       
                    scope","reason":"Forbidden","details":{"kind":"services"},"code":403} 
``` 

If I run `kubectl get svc -n <test-namespace>` it retruns me a list of namespaces. I am on the correct kubectl context.

**Comment by rohank07** [comment]
stack trace: 
```
Traceback (most recent call last):                                                                                     
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 242, in run                                            
                        result = await self._collect_result()                                                                              
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 198, in _collect_result                                
                        scans = await asyncio.gather(*scans_tasks)                                                                         
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 168, in _gather_object_allocations                     
                        recommendation = await self._calculate_object_recommendations(k8s_object)                                          
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 132, in _calculate_object_recommendations              
                        prometheus_loader = self._get_prometheus_loader(object.cluster)                                                    
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 53, in _get_prometheus_loader                          
                        raise result                                                                                                       
                      File "/home/Code/krr/robusta_krr/core/runner.py", line 42, in _get_prometheus_loader                          
                        self._metrics_service_loaders[cluster] = PrometheusMetricsLoader(cluster=cluster)                                  
                      File "/home/Code/krr/robusta_krr/core/integrations/prometheus/loader.py", line 47, in __init__                
                        loader = self.get_metrics_service(api_client=self.api_client, cluster=cluster)                                     
                      File "/home/Code/krr/robusta_krr/core/integrations/prometheus/loader.py", line 62, in                         
                    get_metrics_service                                                                                                    
                        loader = metric_service_class(api_client=api_client, cluster=cluster, executor=self.executor)                      
                      File                                                                                                                 
                    "/home/Code/krr/robusta_krr/core/integrations/prometheus/metrics_service/prometheus_metrics_servic              
                    e.py", line 71, in __init__                                                                                            
                        self.url = self.url or self.prometheus_discovery.find_metrics_url()                                                
                      File                                                                                                                 
                    "/home/Code/krr/robusta_krr/core/integrations/prometheus/metrics_service/prometheus_metrics_servic              
                    e.py", line 34, in find_metrics_url                                                                                    
                        return super().find_url(                                                                                           
                      File "/home/Code/krr/robusta_krr/utils/service_discovery.py", line 74, in find_url                            
                        service_url = self.find_service_url(label_selector)                                                                
                      File "/home/Code/krr/robusta_krr/utils/service_discovery.py", line 30, in find_service_url                    
                        svc_list: V1ServiceList = v1.list_service_for_all_namespaces(label_selector=label_selector)                        
                      File "/home/.local/lib/python3.10/site-packages/kubernetes/client/api/core_v1_api.py", line                   
                    18239, in list_service_for_all_namespaces                                                                              
                        return self.list_service_for_all_namespaces_with_http_info(**kwargs)  # noqa: E501                                 
                      File "/home/.local/lib/python3.10/site-packages/kubernetes/client/api/core_v1_api.py", line                   
                    18346, in list_service_for_all_namespaces_with_http_info                                                               
                        return self.api_client.call_api(                                                                                   
                      File "/home/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 348, in                
                    call_api                                                                                                               
                        return self.__call_api(resource_path, method,                                                                      
                      File "/home/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 180, in                
                    __call_api                                                                                                             
                        response_data = self.request(                                                                                      
                      File "/home/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 373, in                
                    request                                                                                                                
                        return self.rest_client.GET(url,                                                                                   
                      File "/home/.local/lib/python3.10/site-packages/kubernetes/client/rest.py", line 241, in GET                  
                        return self.request("GET", url,                                                                                    
                      File "/home/.local/lib/python3.10/site-packages/kubernetes/client/rest.py", line 235, in request              
                        raise ApiException(http_resp=r)                                                                                    
                    kubernetes.client.exceptions.ApiException: (403)                                                                       
                    Reason: Forbidden                                                                                                      
                    HTTP response headers: HTTPHeaderDict({'Audit-Id': '',                             
                    'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options':                    
                    'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '',                                   
                    'X-Kubernetes-Pf-Prioritylevel-Uid': '', 'Date': 'Wed, 14 Feb 2024                 
                    14:47:11 GMT', 'Content-Length': '269'})                                                                               
                    HTTP response body:                                                                                                    
                    {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services is forbidden:                  
                    User \"<user>\" cannot list resource \"services\" in API group \"\" at the cluster                       
                    scope","reason":"Forbidden","details":{"kind":"services"},"code":403}
```

**Comment by aantn** [comment]
Thanks, looking into it.

**Comment by rohank07** [comment]
Any updates on this?

**Comment by aantn** [comment]
Sorry about the delay. Does #220 fix this for you?
Note that:
1. HPA detection is still broken on #220 (for now) but everything else should work
2. You will have to explicitly specify Prometheus's url with `-p` as auto-detection requires cluster permissions to read all service accounts.

**Comment by rohank07** [comment]
When running `python3 krr.py simple --as system:serviceaccount:<namespace>:krr-account -n <namespace> -p http://127.0.0.1:9090` I get the following for each Deployment in the namespace 
```
           ERROR    Failed to load pods for Deployment <namespace>/<svcName>/<DeploymentName>: 'CustomPrometheusConnect' object has  loader.py:74
                    no attribute 'safe_custom_query'                                                                                                                       
                    Traceback (most recent call last):                                                                                                                     
                      File "/home/user/Code/krr/robusta_krr/core/integrations/prometheus/loader.py", line 72, in load_pods                                               
                        return await self.loader.load_pods(object, period)                                                                                                 
                      File "/home/user/Code/krr/robusta_krr/core/integrations/prometheus/metrics_service/prometheus_metrics_service.py", line 183, in                    
                    load_pods                                                                                                                                              
                        replicasets = await self.query(                                                                                                                    
                      File "/home/user/Code/krr/robusta_krr/core/integrations/prometheus/metrics_service/prometheus_metrics_service.py", line 111, in query              
                        return await loop.run_in_executor(self.executor, lambda: self.prometheus.safe_custom_query(query=query))                                           
                      File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run                                                                             
                        result = self.fn(*self.args, **self.kwargs)                                                                                                        
                      File "/home/user/Code/krr/robusta_krr/core/integrations/prometheus/metrics_service/prometheus_metrics_service.py", line 111, in                    
                    <lambda>                                                                                                                                               
                        return await loop.run_in_executor(self.executor, lambda: self.prometheus.safe_custom_query(query=query))                                           
                    AttributeError: 'CustomPrometheusConnect' object has no attribute 'safe_custom_query'             
```

**Comment by aantn** [comment]
Can you reinstall the python dependencies with --upgrade and make sure
they're up to date?

**Comment by rohank07** [comment]
Thanks that resolved it but I'm now getting 403 error on listing hpa, deployments, statefulsets, jobs and daemonsets

``` 
           ERROR    Will skip this object type and continue.                                                                                                __init__.py:195
           ERROR    Error 403 listing DaemonSet in cluster <cluster>: Forbidden                                                __init__.py:194
                    Traceback (most recent call last):                                                                                                                     
                      File "/home/user/Code/krr/robusta_krr/core/integrations/kubernetes/__init__.py", line 181, in _list_workflows                                      
                        ret_single = await task                                                                                                                            
                      File "/usr/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one                                                                              
                        return f.result()  # May raise f.exception().                                                                                                      
                      File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run                                                                             
                        result = self.fn(*self.args, **self.kwargs)                                                                                                        
                      File "/home/user/Code/krr/robusta_krr/core/integrations/kubernetes/__init__.py", line 170, in <lambda>                                             
                        lambda ns=namespace: namespaced_request(                                                                                                           
                      File "/home/user/.local/lib/python3.10/site-packages/kubernetes/client/api/apps_v1_api.py", line 3181, in                                          
                    list_namespaced_daemon_set                                                                                                                             
                        return self.list_namespaced_daemon_set_with_http_info(namespace, **kwargs)  # noqa: E501                                                           
                      File "/home/user/.local/lib/python3.10/site-packages/kubernetes/client/api/apps_v1_api.py", line 3296, in                                          
                    list_namespaced_daemon_set_with_http_info                                                                                                              
                        return self.api_client.call_api(                                                                                                                   
                      File "/home/user/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 348, in call_api                                       
                        return self.__call_api(resource_path, method,                                                                                                      
                      File "/home/user/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 180, in __call_api                                     
                        response_data = self.request(                                                                                                                      
                      File "/home/user/.local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 373, in request                                        
                        return self.rest_client.GET(url,                                                                                                                   
                      File "/home/user/.local/lib/python3.10/site-packages/kubernetes/client/rest.py", line 241, in GET                                                  
                        return self.request("GET", url,                                                                                                                    
                      File "/home/user/.local/lib/python3.10/site-packages/kubernetes/client/rest.py", line 235, in request                                              
                        raise ApiException(http_resp=r)                                                                                                                    
                    kubernetes.client.exceptions.ApiException: (403)                                                                                                       
                    Reason: Forbidden                                                                                                                                      
                    HTTP response headers: HTTPHeaderDict({'Audit-Id': '9d0d859e-07b8-43ba-8613-594767b7ce64', 'Cache-Control': 'no-cache, private',                       
                    'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid':                                             
                    '', 'X-Kubernetes-Pf-Prioritylevel-Uid': '', 'Date': 'Mon, 04                  
                    Mar 2024 16:56:49 GMT', 'Content-Length': '334'})                                                                                                      
                    HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"daemonsets.apps is forbidden: User                  
                    \"system:serviceaccount:<namespace>:krr-account\" cannot list resource \"daemonsets\" in API group \"apps\" in the namespace                            
                    \"<namespace>\"","reason":"Forbidden","details":{"group":"apps","kind":"daemonsets"},"code":403}  
```

**Comment by aantn** [comment]
I've added support to the PR for reading HPA information with limited permissions. Please check and confirm that it works for you.

**Comment by rohank07** [comment]
This works for me without any issues with HPA. Thank you!
