### ISSUE TITLE
MiMir - grafana agent  - Labels api not present on prometheus client

### ISSUE THREAD

**Issue by mysiki** [robusta-dev/krr#250]
**Describe the bug**
Using mimir and grafana agent, krr canno't work. 

I follow the other issue around mimir, the problem seems to be in the label cluster. But cluster label exist in my setup ...

**To Reproduce**
```
krr simple --prometheus-url https://mimir.XXX/prometheus \
--prometheus-headers 'X-Scope-OrgID: XX' \
--prometheus-label cluster \
-l "CLUSTERNAME" \
--kubeconfig XXX -v
```

I got the error : ERROR    Labels api not present on prometheus client  

This work in my grafana : container_memory_usage_bytes{cluster="XXX"}

**Expected behavior**
working

**Screenshots**
![krr](https://github.com/robusta-dev/krr/assets/19509977/8cb5506f-fc6f-420f-ab78-676b652e89ce)

**Are you interested in contributing a fix for this?**
Yes I can test it but can't have the skill to dev

**Comment by arikalon1** [comment]
Hi @mysiki 

I think KRR should keep working after this error (it should probably be a warning)
Do you have any other error/exception on the logs?
Can you share the entire output?

**Comment by mysiki** [comment]
hey, 

I got this after 

```
 [10:31:06] ERROR    An unexpected error occurred                                                                                                                                                                               runner.py:304
                    Traceback (most recent call last):
                      File "robusta_krr/core/runner.py", line 298, in run
                      File "robusta_krr/core/runner.py", line 246, in _collect_result
                      File "robusta_krr/core/runner.py", line 185, in _check_data_availability
                      File "robusta_krr/core/integrations/prometheus/loader.py", line 75, in get_history_range
                      File "robusta_krr/core/integrations/prometheus/metrics_service/prometheus_metrics_service.py", line 160, in get_history_range
                      File "robusta_krr/core/integrations/prometheus/metrics_service/prometheus_metrics_service.py", line 118, in query_range
                      File "concurrent/futures/thread.py", line 58, in run
                      File "robusta_krr/core/integrations/prometheus/metrics_service/prometheus_metrics_service.py", line 120, in <lambda>
                      File "prometrix/connect/custom_connect.py", line 57, in safe_custom_query_range
                    prometheus_api_client.exceptions.PrometheusApiClientException: HTTP Status Code 500
                    (b'{"status":"error","errorType":"internal","error":"{\\"status\\":\\"error\\",\\"errorType\\":\\"internal\\",\\"error\\":\\"expanding series: failed to fetch some blocks
                    (err-mimir-store-consistency-check-failed). The failed blocks are: 01HT6E3EDKH70N5WF67QWWT66E 01HT6E6961NQ05FSVGF61FXJJB 01HT6E8VYE3CP9CCCVG986EQ64 01HT6EF1H4YXSE4EE7QQ0FE6KK 01HT6EJB715PNWBAHVNM48SS2D
                    01HT6ESNDGJVVYQZ5H63FQS90J 01HT6MWJC5RT54JJMW2BDMCZ5R 01HT6MZ8WVYRB4R9VKZR5K9FKH 01HT6MZ9QQCTFQQN0AEAFN621M 01HT6MZA3GB3W1W6KTQWF0275G 01HT6N2179TVAC2MQTTP4ZXAHW 01HT6N21KFBFZKXDB6CNKSJSER
                    01HT6N24HZQ5NXDNDTJ1RNKSW4 01HT6N4NAAZ5ANGJ0735899FQB 01HT6N4NKFNRC04TZNE3234J9F 01HT6N80G8142ZK227C9KXB5MS 01HT6NAQRMQQKHEBYKSDKHB4NG 01HT6NAR3XSA8Y0PGJG9VJQ6Z3 01HT6NB80CBEHW086VR1PWXF31
                    01HT6NE4140VQF41H2GVNM19R0 01HT6NE4CZKVGAA75E1FBFGJVM 01HT6NJJ4V2P7DJ5EB231MKNT6 01HT6NNB7D544BM32P016445JM 01HT6NNBFQE0ZDG5X227BRZ64C 01HT6VR9M5PKB4Z4A9C8CT8MB6 01HT6VV04V2VKXV9HZRW75XP08
                    01HT6VV0T1PBFD6E8KPREG7VXH 01HT6VV141G2N185NDEG5G4EWK 01HT6VXRTQV69GE0F7YTC6F13V 01HT6VXS10H59CE9VQB0XF422K 01HT6VXVSZX6WF9GR90NV2XRRW 01HT6W0DWQ9GPT2CFNYF1DSWXZ 01HT6W0E2DSZ60KTV21J4DDX2H
                    01HT6W3QR8YW2HJDYYSSP00A4R 01HT6W6FK48ZDEB0B77NTAGFNN 01HT6W6FTP6FA7H5H68RA374C0 01HT6W6Z8BSHA0151A9967CSJQ 01HT6W9XCV6VYH45577WBP4TTN 01HT6W9XJAD5S8F83WEBSNPZPK 01HT6WE9CVZ2VK37MW0F1HJG7P
                    01HT6WH3VFWHAF3DZ3R80WRTGW 01HT6WH476VGKE86PR0GEV4WAD 01HT72M0W5YCSP7H1B6TM276CC 01HT72PQCVSQDJZWT10AYF9ENC 01HT72PQHXA6HEX5F3VWXVRKJT 01HT72PQQWZBH5J6110548PPP9 01HT72SEN2AVNSHC12KE7SZ6GX
                    01HT72SESYQV2N7SRVD7KX10RS 01HT72SK1YS9YP5M2DMHHZ84A6 01HT72W3CQNWXRVM9PMNHFH5HV 01HT72W3J7GKWX1E6BSW5F0QRF 01HT72ZF0865VCGG5BB1EXYXGG 01HT7326221MTNY294VMV3FZ6R 01HT73269E1AWGXG1R54ZTD6FY
                    01HT732PGBF6TX65PWWMBWCJV7 01HT735KC3TE900424M1F561ZM 01HT735KMVG931TX06808J05PM 01HT73A0MVFV2MWWEN32QCGEDP 01HT73CS3STXHWW7K7F1XNEFG5 01HT73CS7XS3GYA9EJJEJJP1QP 01HT79FR45D79AY0A345W4E9M9
                    01HT79JDCDCH4264YE23DCW962 01HT79JDJX904KYNZCCA6GHQJW 01HT79JEMVKQ1RP9XSE56TBXFP 01HT79N7EBY24XN1RYMF17KJ63 01HT79N7NK7Q1JTGX0VE2BW955 01HT79NA9Z1Z9B86Y2497JHPPZ 01HT79QVFAES7P96XY2802209E
                    01HT79QVMFE2V54SV8PR71EXDY 01HT79V6883DWWE3VNKCNEBMSM 01HT79XXFSZ4NB74B0XEHAARVE 01HT79XXNX3WZ9EBYE0DJMBMNJ 01HT79YDRBR2XFW7R7Q2AWR6FM 01HT7A1AGHKVR6T8KWCTYJXK4D 01HT7A1AP34C82G3FC674EZXKQ
                    01HT7A5QWVCNT6H6G5EMCDFNE2 01HT7A8JJKJVZCD8V5X0BVE2F0 01HT7A8JR1ZVAGR8GC8P4YZPY0 01HT7GBFC6PZ8KCYHWWZX54R8Z 01HT7GE5WV8X5AXNKV8319B5RQ 01HT7GE7D0KKW2H1SX5EJGPPB4 01HT7GE7P03S2QF33FX5QXETGN
                    01HT7GGZG0TC2DQ9J0RHC7NSRB 01HT7GGZQQ37W6BZM66K7MRNVT 01HT7GH1HYY1RGB9Y8XFKDDWGG 01HT7GKJNTQ75C1RAEWDMJAKB9 01HT7GKJTTNKK225AMCM012M35 01HT7GPXG800M0EYGBBJAZVCNY 01HT7GSRST4Q2C9GACK1BA79YM
                    01HT7GSRY5CNZE4SQ0YK5S4BNV 01HT7GT50BJYDW96N4HMJEKMVD 01HT7GX45MC5B7Y58JFBR20HJJ 01HT7GX4E798ASPH9MV0ZYCR06 01HT7H1F4V4M5MNA66J85C2PWV 01HT7H4BZFATCB5HRTPW2CPZ65 01HT7H4C3XQZX88HTHXSQCJ10K
                    01HT7Q76M5J8GGDCSEGHYB5BDZ 01HT7Q9X4VTRKSF03FEX032E04 01HT7QA0WZKYWK0TN42J9KQAHA 01HT7QA13SM8RJQ5BJT3V69H8K 01HT7QCRSYDXFJ7W3NJ3RSDEWB 01HT7QCTR4CVE5F09FBV6F57PM 01HT7QCVAFHN2MZHNQ5TA7PN63
                    01HT7QFDVJHBKQ24T79X7H3NPZ 01HT7QFE07K60NT2NMKVG5J4EC 01HT7QJMR8WJ6P019GRJWVKN49 01HT7QNJ0H64A2V1DP7M0EHJPG 01HT7QNJ8WYJ5BCCMCRS1AXW9F 01HT7QNW8BCQ5Z9KKRPKKWN0J7 01HT7QRWD1AYZ5EX22WRJE69N2
                    01HT7QRWJXV6KFKQ3QDXC0N17W 01HT7QX6CV80JKC0GP9NJA4QFT 01HT7R04MQ88D53YB1SNYG2BTE 01HT7R04TYKYSZWNBKSJ66B7R6 01HT7Y2XW5QHJFQSCVE2VEP137 01HT7Y5JRFS02SDCZ6A74GRSD1 01HT7Y5K1PXHC3RA1JZR0FYZER
                    01HT7Y5MCVG6A3J50PTKN6APBW 01HT7Y8CJH03NQJV8VK3PNJMV8 01HT7Y8CT2PGB0FH41394ETF8M 01HT7Y8G1Y7GP4YYY9VTQYRWTT 01HT7YAZYN4WXSMR24W6ACNA0J 01HT7YB04WZ9C28YPWEB9YYJQR 01HT7YEC09RS0Z5EFXG16C4406
                    01HT7YH226EYAQTZB1W4EQYVRZ 01HT7YH26T06A50081H622BN9Q 01HT7YHKGBQJPKAKR8YGNBV19C 01HT7YMFC8DA34QAH4JQXW74VQ 01HT7YMFNM6J9N4AX85F1AV702 01HT7YRXMVEDVVWT5KB7DZTN0S 01HT7YVP6PREJG8TBF44T6B89E
                    01HT7YVPAQ621C4T3ZA78CQK5M 01HT84YN45K10A178RQ7E56SJ3 01HT851AV8QKQ59ZFV4FNZNTQ6 01HT851B3E1NRYD3SZG280SJMW 01HT851BMVHED04C9QMT6QBFVY 01HT8544RMGTGGMJ42N3E4TTY5 01HT854535EMEXZHN80S1KJK2N
                    01HT85479ZPX0HPQW72ZHAFH0Y 01HT856N9BYX13646ARH513WB3 01HT856NFJ5H0AR8B781HGWV2R 01HT85A388JBS8S3XYMYA7MKJF 01HT85CTCGV7MG9NVN1SQ3XT6R 01HT85CTK03AYESR5693PV9QTD 01HT85DARB1XGSQ11GAMTFXK9M
                    01HT85G5MZCD0XFY8F5N78B807 01HT85G5SBXGS6S90NGPAYPJPN 01HT85MMWVEVJF8BN5ASXTXGF5 01HT85QF9DQY18H00288STG8GH 01HT85QFFY6N1SS6SZTQ2NSDE5 01HT8BTCC6DDYDF3QD2WTS9E03 01HT8BX21E861D1M4N1JYYYMQP
                    01HT8BX26R847AZBFQH6NTMVE7 01HT8BX2WVVBSAQ71FG9X6XHTT 01HT8BZVHKPC2GAVQTN1KY1J18 01HT8BZVS2W95N0D53PX34PFRV 01HT8BZYHY7RS6BQSPHG7CPXV9 01HT8C2D8549JMFVDZCCT85J92 01HT8C2DCCS1S45PJGQ1517KY5
                    01HT8C5TG8A5WNJ31EBEBF5ZYK 01HT8C8KD45NM3DMHJ5KKSV568 01HT8C8KK80MNJ2C1NSHBQESXK 01HT8C920BK9TEPH70WEJED623 01HT8CBXS7BTVK09XDG3CDP44B 01HT8CBXZ66XDRMJ9AKGJJJHCZ 01HT8CGC4V21HN1BAX1BECHZWS
                    01HT8CK40ZPBFR7D04CMQ1877N 01HT8CK460EZDSMPMMAFKQN8R3 01HT8JP3M6V8JDP9XM600AJHHD 01HT8JRSHNC2VT9TQ8089AS58X 01HT8JRSPNPX9RAZAMFP985AV2 01HT8JRT4VTTPZJMFDJC8JGRQK 01HT8JVH21YA4973Y2DJ4JMPA9
                    01HT8JVHA592E7EMFF2X1BHV81 01HT8JVNSYT68E2BS47A997K1X 01HT8JY3QFYZX1AGSCYJJ5XPHM 01HT8JY3WZSWRAXR45TTM9JBKG 01HT8K1HR8E51PG39Y3CGANQ6X 01HT8K48430TZA75XAF3VFENEH 01HT8K488Z30YPPVGBPCBWJSPH
                    01HT8K4S8BVN7TMX1HXR5212ZK 01HT8K7MBXVSXBEG46NSC4RANM 01HT8K7MHC2HV968MRCRMEKYSH 01HT8KC3CV59AXD1QGDJK3A3RZ 01HT8KEYB9YC775X5EFRN1AS9V 01HT8KEYFSNJXR3RAXGM96Q7MW 01HT8SHTW5Z7J3NQGGFK674SEM
                    01HT8SMGASD9G9R5KQTMHKXK87 01HT8SMGJYN0WP6PZTC4180JWJ 01HT8SMHCVYJES6B9P2S54BMMR 01HT8SQ7CZW9H2PCPH3AMTBFQ0 01HT8SQ7JD5WYHPZM258F5APG7 01HT8SQD1YPMTZZJ1BSPYGYS96 01HT8SSTFZAAZRMYNTQVD80H8Z
                    01HT8SSTPH3PWPD915HP25RDDQ 01HT8SX9098ZRP9KEWJQW5GZEA 01HT8T01ZAXKDZCP47VHCXV6GX 01HT8T026PM5Q5PMVABJHQEK9R 01HT8T0GGB4F53TGQR5GE0PA9D 01HT8T3CT0JK6BT5JF5D091T49 01HT8T3CYV5W68K5H885W7KAQE
                    01HT8T7TMVH1E0AG9EGR9VTEET 01HT8TAKEBRET64QG9S55QJX2H 01HT8TAKK9R4BKVBAE12W6MJZE 01HT90DJ45PWG5E0BXS99ZZJQG 01HT90G86QS7RMHF2WJ1GWCMNT 01HT90G8MV5JH8P471YPF74QX9 01HT90K1TZV9Q8CY6N5689KD7P
                    01HT90K49YCPT5MFZ7Z5NYNF9A 01HT90NNDSVQ3R5AQZ6R8Z0WXG 01HT90S0885D63E582YMPZVWQ7 01HT90VR2VE46RN2HY3T0SXSNN 01HT90W7RB0218YFG9EJM57HC5 01HT90Z497P6SD1FQSCDNXX2CY 01HT913HWV32DCSH3W131ZRR31
```

**Comment by arikalon1** [comment]
Thanks @mysiki 

On 1.7.1 we ran a heavy query, to check if there's enough data to run the scan.
Looks like this query fails on Mimir

We already fixed this, but it wasn't released yet

We're going to release a version with this fix very soon

Once we do, I'll ask you to upgrade, and check if you still get the same issue

**Comment by mysiki** [comment]
If you need, I can do some test to validate the release. Event if I not mastering in monitoring part :D

**Comment by arikalon1** [comment]
hey @mysiki 

We just released 1.8.2
Can you please check if the issue exists in this version as well?

**Comment by mysiki** [comment]
Yeah I see it, just testing now :D 

I got the same kind of error ... I also saw that if I use my kubeconfig file, it not work (event in new fresh container). Does the kubeconfig need to have special content ? 

```
[22:17:30] ERROR    An unexpected error occurred                                                                                                                                                                               runner.py:336
                    Traceback (most recent call last):
                      File "robusta_krr/core/runner.py", line 329, in run
                      File "robusta_krr/core/runner.py", line 283, in _collect_result
                      File "robusta_krr/core/runner.py", line 243, in _gather_object_allocations
                      File "robusta_krr/core/runner.py", line 188, in _calculate_object_recommendations
                      File "robusta_krr/core/integrations/prometheus/loader.py", line 113, in gather_data
                      File "robusta_krr/core/integrations/prometheus/loader.py", line 114, in <dictcomp>
                      File "robusta_krr/core/integrations/prometheus/metrics_service/prometheus_metrics_service.py", line 186, in gather_data
                      File "robusta_krr/core/integrations/prometheus/metrics/base.py", line 182, in load_data
                      File "robusta_krr/core/integrations/prometheus/metrics/base.py", line 148, in query_prometheus
                      File "concurrent/futures/thread.py", line 58, in run
                      File "robusta_krr/core/integrations/prometheus/metrics/base.py", line 148, in <lambda>
                      File "robusta_krr/core/integrations/prometheus/metrics/base.py", line 129, in _query_prometheus_sync
                      File "prometrix/connect/custom_connect.py", line 89, in safe_custom_query
                    prometheus_api_client.exceptions.PrometheusApiClientException: HTTP Status Code 500
                    (b'{"status":"error","errorType":"internal","error":"{\\"status\\":\\"error\\",\\"errorType\\":\\"internal\\",\\"error\\":\\"expanding series: failed to fetch some blocks
                    (err-mimir-store-consistency-check-failed). The failed blocks are: 01HSPHZQRB3CG08PR9WBQRNVHN 01HSQ061T6P0Q449BE1WMWZGVD 01HSQMA9SV8TY4NNS85RRTE4C1 01HSQMD2PPPE0AKRPJ0KGYC6ZP 01HSQN0EW6SN0SJ9GJDF17RC1D
                    01HSQV3E45F3N1NZBRZHZT53H5 01HSQV909YAT22T8TCQJMDYB9Y 01HSR275F2N24NRZ992VYYV459 01HSR2GN6AJ1Z7H69TJ9KRT66W 01HSR92WNP8EWB3MJ78D7BFA8X 01HSR96AR8THRPKC6KJEXRFF6P 01HSRFSACV845WFTVHY2GYBACF
                    01HSRFW1BZ5X455A7FDK7WP4N6 01HSRFYJ1KBWPP9638F0238PQY 01HSRG4QW6EW9TV5NMP3WA32FS 01HSRG82YX3R23FK32H57DWF22 01HSRPMXD0JDWKMP5HAFQ5MAVJ 01HSRPN1MVD5B4CAHBAB5QY94Q 01HSRQ10RBXH6KPXQVD72AR0GS
                    01HSRQ3TYCMBS987Y0KM3MT0E3 01HSRXSGG8N5FBVADDM3FDRPN6 01HSRY6PYDVKVV6EF7QPNQMNKC 01HSS4N7R96JMRYZXWRWN6JR43 01HSS52GCE27PF4HA7R5C8FQCJ 01HSSBAWVRQK1M53GK88QJC5KT 01HSSBGZ080T0YW8GMP636D0W6
                    01HSSBQ27BFEYFBQHZ6D2KESV7 01HSSJ3V6J4ZVPG57XMZ9HW607 01HSSJCP88TDMXQN9GNXR2GCHA 01HSSJJQVW0PXB7A74ZWEMJH7G 01HSSJQ7WVZE1YY1RTJ5XNXZRP 01HSSRWZC6H89N3T5TGBDA0R51 01HSSS2EFR8FMQRFPTCTC4KZK4
                    01HSSSB1VNDVKS1EN8YMNGPNKK 01HSSZV9F42ZM2S0CQJ01G740B 01HSSZVD4VFD6HFAPNM52EVSW0 01HST06T33C4AJ7G1W131ZZNGB 01HST07C8BYG3EVFTEAQA47611 01HST6Q0P17WXFT7YSW0E2VCP1 01HST6Q4CW0X5EZW2640SG2PNZ
                    01HST7ADMVZ1KBGFE6DCGSSYGV 01HSTDNK9YFZKG7PKD5SRM9AWB 01HSTDR5Q52MQWR576P8VXST0N 01HSTDYA8H71E5NHTZP578XGG9 01HSTE1M91B7089AKNMQNEQEY7 01HSTMHCFQK9B47DMD3EE402SV 01HSTMMFZN6HGG54ZS9TRHBFWX
                    01HSTMMGEX5NM5KG1GXBN18WGP 01HSTMT1EFXB0ECBX9HB5GDQQ4 01HSTMTJ0BW83ZDKYC2MV5E9HM 01HSTN4KXZEA9V8R08G01ZQVQS 01HSTV7KM5J6238PHJ3TSEDYNK 01HSTVA7GTFERMJ2NB0W9EPBDV 01HSTVD1B0C466ZHA0YAG0C2CS
                    01HSTVS41A841BDNDR4FQYBRBX 01HSV261CVPTQ8C84CG1GW0WER 01HSV28X1Y10Z1GSM13E9QH9R0 01HSV2HQKP8FVYE08760S3PRBZ 01HSV91RYC94XVPNB79PBB4GAR 01HSV94KPNGJN1HWHA2HX8F41B 01HSV97NPQX3QHTSD9RTT1QVFJ
                    01HSV97P4ZJE9N8MMFEJ1Q1WCB 01HSV9DC4MZYY17J9679YYM110 01HSV9DCJ7KFSH96EE4M2VCJ0W 01HSV9DQRBZF5K2MPFCWR0ZP97 01HSV9QXPB24CMPP86Q8DAAGDE 01HSVFTSC8FFKM0A9904EVKCSX 01HSVFXFA416NVJDN0DZR4ZWY7
                    01HSVFXFWVBYG513XXEJSMJ32T 01HSVG09HE7A6R05HBKNA4CBEB 01HSVG09X02J56XQSRVDXH4968 01HSVG0BHYEWVZRT7JH8YJ3BJC 01HSVG2WDB02Z4X6B55P9DM1SX 01HSVG67G8FX4FNNJBB5Z2G8K9 01HSVG8ZJY7K7FCECYVV5C6KSX
                    01HSVG8ZXNW3TWXDGQCZ733FPE 01HSVG9F0BM00RHJR2066GRGT7 01HSVGCCD8K7TY15MVYK3C8FQ2 01HSVGCCRCNTF1W1GR07WVNTYH 01HSVGGS4VD6BF9882345TQAV6 01HSVGKNHDSBFHQREHA9ASBC06 01HSVGKNXD0WEYCAQJSFVCRK7C
                    01HSVPPGM65C7DBBZJWMC3EZG2 01HSVPS5AQPM3BN1NNJPATC9Y0 01HSVPS5KM4WABPGNXQDCZ15B3 01HSVPS74V2EE8PH1P3EA2P8RT 01HSVPW1AJDMZRKJ3QGCDQ0PTD 01HSVPW1K1JJ3MAWA38TE7FVRP 01HSVPW2SYB7A3J6229T0H1KCW
                    01HSVPYMQYER0NHP9T7TNN2MZV 01HSVPYMYHYFMTHMWZF1QETNGK 01HSVQ1YR89KFSWN2XQWPHC2XS 01HSVQ4QYJHX44ZYE9214TJCH0 01HSVQ4R5N0525J306GNTN5476 01HSVQ568BRHVR2A5XSTJAWKCZ 01HSVQ844NSZECJ068JNSRPADP
                    01HSVQ84AY5BGEABS97J3GBG5F 01HSVQCGCV2Z2EA8T2JPSJC9Z3 01HSVQFB1GPNYRMXY5FNAGW09V 01HSVQFB7FPQSWZEE6RM0CN50Y 01HSVXJ7W5X9SMZH7HS9ZWVQZW 01HSVXMXBJWMJ65CF5ACZVKD5V 01HSVXMXRCK4N334J7SZ39W7Q6
                    01HSVXMYCVTJNWKM271WKPFBN9 01HSVXQRZX2NMCS4VD014KHSDK 01HSVXQSA0V3P8R08PHTEZKAZH 01HSVXQT1ZQEGXJA35R7R0SP55 01HSVXTT6CEEWSTPRQP1454T6H 01HSVXTTJB6Y1F9M1N5WBBHE7C 01HSVXXP09J85KT4059G5FPVN6
                    01HSVY0DPPAMC0JBDKETA6MYKM 01HSVY0E3BB3558XQN8G2A89GY 01HSVY0XGB07QQVF34KK22AANW 01HSVY3VPYN20M1DJNW0V8M899 01HSVY3W32D539S7A4BP3FJMD4 01HSVY87MVETASYDA4A8K53YZ5 01HSVYB3C31TDVC398YD2NPKKS
                    01HSVYB3RMY0XBH0YEPF80FDVN 01HSW4DZ45H13J17TNVDGAAXEH 01HSW4GN87BK773KAQBXZS6RER 01HSW4GNMV5YDJA8DWDMVEM6YT 01HSW4GNP0E6EQC265HHN1E3K2 01HSW4KEWM5Y3CZQPW1PZ32C07 01HSW4KFA90M9X8T68HYBN8YBE
                    01HSW4KH9Y223B3FHYQ6M97Y1K 01HSW4P45EEV3MQWPCYZDNN7S9 01HSW4P4GF9THGVRRDTC613J7Q 01HSW4SD88XQNHSC5CEJC8XJC2 01HSW4W7NR5MFKHQ16701AW3MC 01HSW4W83TE3QK0WGCAJ4679CY 01HSW4WMRBRGZSX9QK8Y7RH3WJ
```

I will check this week with my Mimir guy if it's something in my side

**Comment by mysiki** [comment]
I seems to be in my side, because of space error. Let check tomorrow after merge job

**Comment by mysiki** [comment]
hey, with last version it seems to work. I saw than last version add mimir auto discovery but missing to update the documentation :D 

For me, my issue is close

**Comment by aantn** [comment]
@mysiki thanks, happy to hear it. Which docs did we forget to update?

**Comment by mysiki** [comment]
@aantn  The readme :) nothing about Mimir (compatibilities and usage). In fact, I use prom-url event if mimir auto discovery work because I don't know how to use it

**Comment by aantn** [comment]
@pavangudiwada can you please update and add Mimir to the readme?
