### ISSUE TITLE
--resource flag broken in 1.11.0

### ISSUE THREAD

**Issue by LukasPrediger** [robusta-dev/krr#314]
**Describe the bug**
Using the --resource flag causes an exception when running the program

```
[15:43:10] ERROR    An unexpected error occurred                                                                                                                                                                                     runner.py:342
                    Traceback (most recent call last):
                      File "robusta_krr/core/runner.py", line 335, in run
                        result = await self._collect_result()
                      File "robusta_krr/core/runner.py", line 288, in _collect_result
                        workloads = await self._k8s_loader.list_scannable_objects(clusters)
                      File "robusta_krr/core/integrations/kubernetes/__init__.py", line 531, in list_scannable_objects
                        return [
                      File "robusta_krr/core/integrations/kubernetes/__init__.py", line 534, in <listcomp>
                        for object in await cluster_loader.list_scannable_objects()
                      File "robusta_krr/core/integrations/kubernetes/__init__.py", line 73, in list_scannable_objects
                        return [
                      File "robusta_krr/core/integrations/kubernetes/__init__.py", line 76, in <listcomp>
                        for object in workload_objects
                    TypeError: 'NoneType' object is not iterable
```
**To Reproduce**
1. Checkout v1.11.0 tag
2. Run krr with `simple --resource Deployment`
3. get error

**Expected behavior**
Should run krr skipping all kinds except Deployment

**Desktop (please complete the following information):**
- v.1.11.0

**Additional context**
This is probably caused by the kubernetes integration. The guard statements return None instead of an empty list.
https://github.com/robusta-dev/krr/blob/c400fc85f0ad1f772fabdf1f43d4d03cc3f25658/robusta_krr/core/integrations/kubernetes/__init__.py#L224-L237

**Comment by aantn** [comment]
Thanks for reporting and you are spot on with the fix. Opening a PR to fix.
